# Site settings
title: Jeff Miller's Technical Blog
email: jmillersiu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog intended to reach anyone who may want to read about me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmiller70.github.io" # the base hostname & protocol for your site
twitter_username: Miller_Tym
github_username:  jmiller70

# Build settings
markdown: kramdown
